### ISSUE TITLE
document title

### ISSUE THREAD

**Issue by obgm** [obgm/ace-dtls-profile#2]
We have discussed adding 'CoAP' to the document title to express the assumption that this profile is for CoAP messaging over DTLS between C and RS. 
The drawback is that the title will get very long due to the abbreviation-unfolding requirement.

**Comment by LudwigSeitz** [comment]
I'm not in favour of overly long titles. Unless there is a way to get around the abbreviation unfolding I'd be against this change

**Comment by obgm** [comment]
Okay, Thanks. As I share your opinion, I close this ticket without changing the title (so far, no one seems to have missed the "CoAP" addition anyway).
